#!/usr/bin/env python3
"""Regenerate ``internal/INDEX.md``'s catalogue section.

WHY THIS EXISTS
---------------
``internal/`` is gitignored (leak-shield: it holds private planning, customer
dogfood corpora and unreleased strategy). Being untracked has a cost nobody
noticed: an agent — or a person — pointed at "the internal docs" gets whatever
happens to be on that machine, with no reliable way to find out what is there.

On 2026-07-28 the tree held **2053** markdown files while ``internal/INDEX.md``
was 50 lines, last edited 2026-07-12, and named none of the five most recent
documents — including the defect inventory that a same-day fix was working
from. The index had silently become a stub, and because the directory is
untracked, no CI check and no review could see that happen.

WHAT IT DOES
------------
Rewrites ONLY the region between the AUTO markers below, so the hand-written
preamble above it (the "rule of thumb" filing convention, which is real human
judgement and must not be machine-clobbered) survives untouched:

    <!-- AUTO-CATALOGUE: regenerated by dev/build_internal_index.py -->
    ...generated...
    <!-- /AUTO-CATALOGUE -->

Root-level docs are catalogued individually — per the index's own filing rule
those are the live campaign documents, the ones worth naming. Subdirectories
are summarised by count instead: ``benchmarks/`` alone holds ~1669 result
dumps, and listing them would bury the 59 documents that actually carry intent.

PRIVACY
-------
This script is tracked and public; its OUTPUT is not. It only ever writes
inside ``internal/``. It must never copy internal titles into a tracked file —
if you extend it, keep that invariant.

USAGE
-----
    python dev/build_internal_index.py            # check only, exit 1 on drift
    python dev/build_internal_index.py --write    # regenerate

Exits 0 when ``internal/`` is absent — that is the normal state on public CI
and on a fresh clone, and is not an error.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

START = "<!-- AUTO-CATALOGUE: regenerated by dev/build_internal_index.py -->"
END = "<!-- /AUTO-CATALOGUE -->"

# Filenames embed their own ISO date; prefer it over mtime, which any
# checkout or rsync resets. (Deliberately no literal example here -- the
# leak gate matches that filename SHAPE, and it caught this very comment.)
DATE_IN_NAME = re.compile(r"(20\d{2}-\d{2}-\d{2})")


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _title_and_gist(path: Path) -> tuple[str, str]:
    """First ``# heading`` and first ``> blockquote`` line, both optional."""
    title, gist = "", ""
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for _ in range(40):
                line = fh.readline()
                if not line:
                    break
                stripped = line.strip()
                if not title and stripped.startswith("# "):
                    title = stripped[2:].strip()
                elif not gist and stripped.startswith("> "):
                    gist = stripped[2:].strip()
                if title and gist:
                    break
    except OSError:
        return "", ""
    return title, gist


def _clip(text: str, limit: int) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def build_catalogue(internal: Path) -> str:
    roots = sorted(
        (p for p in internal.glob("*.md") if p.name != "INDEX.md"),
        key=lambda p: (
            DATE_IN_NAME.search(p.name).group(1) if DATE_IN_NAME.search(p.name) else "0000-00-00",
            p.name,
        ),
        reverse=True,
    )

    subdirs = []
    for d in sorted(p for p in internal.iterdir() if p.is_dir()):
        count = sum(1 for _ in d.rglob("*.md"))
        if count:
            subdirs.append((d.name, count))

    total = len(roots) + sum(c for _, c in subdirs)

    out: list[str] = [START, ""]
    out.append(
        f"*Generated {date.today().isoformat()} — {total} markdown files "
        f"({len(roots)} at root, {sum(c for _, c in subdirs)} nested). "
        "Regenerate with `python dev/build_internal_index.py --write`.*"
    )
    out.append("")
    out.append("### Root documents")
    out.append("")
    out.append("| Date | Document | What it covers |")
    out.append("|---|---|---|")
    for p in roots:
        m = DATE_IN_NAME.search(p.name)
        when = m.group(1) if m else "—"
        title, gist = _title_and_gist(p)
        blurb = _clip(gist or title, 110) or "—"
        out.append(f"| {when} | `{p.name}` | {blurb} |")

    if subdirs:
        out.append("")
        out.append("### Subdirectories")
        out.append("")
        out.append("Summarised by count — these hold generated results and corpora, not intent.")
        out.append("")
        out.append("| Directory | Files |")
        out.append("|---|---|")
        for name, count in sorted(subdirs, key=lambda kv: -kv[1]):
            out.append(f"| `{name}/` | {count} |")

    out.append("")
    out.append(END)
    return "\n".join(out)


def splice(existing: str, catalogue: str) -> str:
    if START in existing and END in existing:
        head = existing.split(START)[0]
        tail = existing.split(END, 1)[1]
        return head + catalogue + tail
    # First run: append, preserving every hand-written line above.
    return existing.rstrip() + "\n\n" + catalogue + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="rewrite the catalogue in place")
    args = ap.parse_args()

    internal = _repo_root() / "internal"
    if not internal.is_dir():
        # Public CI and fresh clones have no internal/. Not an error.
        return 0

    index = internal / "INDEX.md"
    existing = index.read_text(encoding="utf-8") if index.exists() else "# internal/ — Index\n"
    updated = splice(existing, build_catalogue(internal))

    if updated == existing:
        print("[internal-index] INDEX.md catalogue is current.")
        return 0

    if args.write:
        index.write_text(updated, encoding="utf-8")
        print("[internal-index] regenerated internal/INDEX.md")
        return 0

    print(
        "[internal-index] internal/INDEX.md catalogue has drifted.\n  fix: python dev/build_internal_index.py --write",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
